sudo: false
cache: pip
language: python
python:
- 3.6
install:
  - sh -c "cd ddot/mhk7-clixo_0.3-cec3674/ && make all"
  - sh -c 'if [ "$TOXENV" = "py" ]; then pip install tox codecov; else pip install tox; fi'
script:
  - tox -e py
after_success:
  - sh -c 'if [ "$TOXENV" = "py" ]; then tox -e coverage-report; codecov; fi'
